### ISSUE TITLE
google module

### ISSUE THREAD

**Issue by cyberkore** [ZonkSec/google-analytics-attack-ng#1]
Hello, when i try to start the script i get this error.
```
Traceback (most recent call last):
  File "google-analytics-attack-ng.py", line 7, in <module>
    import google
ImportError: No module named google

```
I also tried to run 

`pip install google`

and i get this
```
Requirement already satisfied: google in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python2.7/dist-packages (from google)
```

Any ideas?

**Comment by ZonkSec** [comment]
Hi! The script needs python3. Looks like you are installing the python libraries for your 2.7 environment.  Typically, you use pip3 to install libraries into python 3 environment.  Hopefully that helps! Thanks.

**Comment by cyberkore** [comment]
Hello, tnx for the answer but i solved using pigar for requirements.

**Comment by ZonkSec** [comment]
nice! feel free to make a pull request with it for others. thanks!
